Main svc
GeorgyMalkhozov/java-explore-with-me pull request #2
Opened 2023-03-19 21:05 UTC by GeorgyMalkhozov

2023-03-20 20:43 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryService.java
> +public class CategoryService {
Сервисы должны наследоваться от интерфейсов

2023-03-20 20:51 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/compilation/service/CompilationService.java
> +    public CompilationDto addCompilation(NewCompilationDto dto) {
Почему ты не используешь @Transactional ?

2023-03-20 20:54 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/compilation/service/CompilationService.java
> +        Compilation compilation = compilationDao.getCompilationById(compilationId);
В этой функции уже вызывается checkCompilationExist. Получается лишний вызов.
Еще на что можно обратить внимание это то, что checkCompilationExist по сути вытаскивает объект, проверяет, что что-то вытащилось и дальше выкидывает эксепшн, но вытащенный объект забывается и потом он снова вытаскивается. Попробуй сделать так, чтобы обращение к базе данных было одно, т.к. каждое обращение к базе данных очень затратно по времени

2023-03-20 21:00 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/MainService.java
> +@ComponentScan(basePackages = "ru.practicum")
Тут не нужен ComponentScan, т.к. он содержится в верхней аннотации

2023-03-20 21:03 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/event/dao/EventDao.java
> +    public Event getEventById(Long id) {
DAO объект выполняет роль сервиса. Лучше чтобы каждый выполнял свою обязанность.

2023-03-20 21:04 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/event/dao/EventDao.java
> +        event.setConfirmedRequests(participationRequestRepository.countAllByEventIdAndStatus(id,
Если есть желание, попробуй написать селект, чтобы обращаться к базе данных один раз, а не два

2023-03-20 21:07 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/request/service/ParticipationRequestService.java
> +        return participationRequestMapper.participationRequestToDto(participationRequest);
Если есть желание, попробуй написать один селект вместо семи. Старайся обращаться к базе данных как можно меньше.

2023-03-20 21:09 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/request/service/ParticipationRequestService.java
> +                        participationRequestDao.checkEventIsNotFullyBooked(event);
Тут дао выполняет роль сервиса.
Еще проверка event'a делается в цикле, но проверяется один и тот же объект

2023-03-20 21:12 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/request/service/ParticipationRequestService.java
> +                        participationRequestDao.saveRequest(request);
Попробуй убрать обращение к базе каждый раз в for. Вместо этого попробуй использовать saveAll(), чтобы использовать batch

2023-03-20 21:16 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/controller/PublicController.java
> +            @RequestParam(defaultValue = "10") Integer size,
Проверь точно ли сюда нельзя в size передать ноль? Дальше ты делишь на size

2023-03-20 21:21 UTC, EvgenyKoptubenko commented
Если отправить такой запрос 
curl --request POST \
  --url 'http://localhost:8080/users/1/events?from=0&size=1' \
  --header 'Content-Type: application/json' \
  --data '{}'

То приходит очень длинный ответ

{
	"errors": [
		"MethodArgumentNotValidException"
	],
	"message": "Validation failed for argument [1] in public org.springframework.http.ResponseEntity<java.lang.Object> ru.practicum.controller.PrivateController.addEvent(java.lang.Long,ru.practicum.event.dto.NewEventDto) with 6 errors: [Field error in object 'newEventDto' on field 'category': rejected value [null]; codes [NotNull.newEventDto.category,NotNull.category,NotNull.java.lang.Long,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [newEventDto.category,category]; arguments []; default message [category]]; default message [категория не должна быть пустой]] [Field error in object 'newEventDto' on field 'eventDate': rejected value [null]; codes [NotNull.newEventDto.eventDate,NotNull.eventDate,NotNull.java.time.LocalDateTime,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [newEventDto.eventDate,eventDate]; arguments []; default message [eventDate]]; default message [дата события не должна быть пустой]] [Field error in object 'newEventDto' on field 'title': rejected value [null]; codes [NotNull.newEventDto.title,NotNull.title,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [newEventDto.title,title]; arguments []; default message [title]]; default message [название должно быть от 3 до 120 символов]] [Field error in object 'newEventDto' on field 'location': rejected value [null]; codes [NotNull.newEventDto.location,NotNull.location,NotNull.ru.practicum.location.dto.LocationDto,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [newEventDto.location,location]; arguments []; default message [location]]; default message [локация не должна быть пустой]] [Field error in object 'newEventDto' on field 'annotation': rejected value [null]; codes [NotNull.newEventDto.annotation,NotNull.annotation,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [newEventDto.annotation,annotation]; arguments []; default message [annotation]]; default message [аннотация должна быть от 20 до 7000 символов]] [Field error in object 'newEventDto' on field 'description': rejected value [null]; codes [NotNull.newEventDto.description,NotNull.description,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [newEventDto.description,description]; arguments []; default message [description]]; default message [описание должно быть от 20 до 7000 символов]] ",
	"reason": "Некорректный запрос",
	"status": "BAD_REQUEST",
	"timestamp": "2023-03-20 21:19:39"
}

Попробуй сократить сообщение об ошибке, т.к. присутствует информация, которая по сути не нужна клиенту.

2023-03-20 21:22 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть несколько предложений по улучшению кода

2023-04-06 11:37 UTC, GeorgyMalkhozov commented
Внес правки по всем замечаниям, кроме двух по селектам - обязательно внесу их на финальном этапе, сейчас очень сроки поджимают (

2023-04-06 23:58 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-04-07 11:56 UTC, merged